POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbXBwYSIsImlkIjoiNjQ2MjY2NzQ2OTNlZDE4OTNiZDAwNTFkIiwiaWF0IjoxNjg0MjQ0Mzc4fQ.dxmLHd_1txomNESFd1_qM7Mvq93cLixYX31Z-Eo4EhU

{
    "title": "Blogi 3",
    "author": "Janne Tulkku",
    "url": "https://www.blogi3.fi",
    "likes": 3
}
